framework:
    rate_limiter:
        contact_mail:
            policy: 'token_bucket'
            limit: 5
            rate:
                interval: '1 minute'
                amount: 5
        image_upload:
            policy: 'token_bucket'
            limit: 30
            rate:
                interval: '1 minute'
                amount: 30

