parameters:
    image_upload_dir: '%env(resolve:IMAGE_UPLOAD_DIR)%'
    image_base_url: '%env(IMAGE_BASE_URL)%'
    image_max_size: '%env(int:IMAGE_MAX_SIZE)%'
    image_api_key: '%env(IMAGE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\ContactMailController:
        arguments:
            $contactMailLimiter: '@limiter.contact_mail'

    App\EventSubscriber\CorsSubscriber:
        arguments:
            $allowedOrigin: '%env(CORS_ALLOW_ORIGIN)%'

    App\Service\ImageService:
        arguments:
            $uploadDir: '%image_upload_dir%'
            $baseUrl: '%image_base_url%'
            $maxSize: '%image_max_size%'

    App\Controller\ImageController:
        arguments:
            $imageUploadLimiter: '@limiter.image_upload'
            $apiKey: '%image_api_key%'
